---
- name: install and configure mariadb
  hosts: db
  tasks:
  - name: Install mariadb
    yum:  "pkg={{ item }} state=latest"
    with_items:
      - mariadb
      - mariadb-server
      - MySQL-python
      - php-mysql

  - name: Ensure MySQL is properly configured
    template:
      src: templates/my.cnf.j2
      dest: /etc/my.cnf

  - name: Empty MySQL log
    file:
      path: /var/log/mysqld.log
      state: touch
      owner: mysql
      group: mysql
      mode: 0775

  - name: Ensure the MariaDB PID folder is present
    file:
      path: /var/run/mysqld
      state: directory
      owner: mysql
      group: mysql
      mode: 0775

  - name: Open port
    firewalld: "port=3306/tcp state=enabled zone=public permanent=yes immediate=true"

  - name: start and enable mariadb
    service: "name=mariadb state=started enabled=yes"

  - name: Ensure the application db is present
    mysql_db:
      name: '{{ dbname }}'
      state: present

  - name: Ensure the MariaDB db is present
    mysql_user:
      name: '{{ dbuser }}'
      password: '{{ dbpass }}'
      priv: '*.*:ALL'
      host: '%'
      state: present
