---
- name: install and configure mysql
  hosts: all
  tasks:
  - name: Install mysql
    yum:  "pkg={{ item }} state=latest"
    with_items:
      - mariadb-server
      - MySQL-python
      - php-mysql

  - name: Ensure MySQL is properly configured
    template:
      src: templates/my.cnf.j2
      dest: /etc/my.cnf

  - name: Open port
    firewalld: "port=3306/tcp state=enabled zone=public permanent=yes immediate=true"

  - name: start and enable httpd
    service: "name=mariadb state=started enabled=yes"

  - name: Ensure the application db is present
    mysql_db:
      name: '{{ dbname }}'
      state: present

  - name: Ensure the MariaDB db is present
    mysql_user:
      name: '{{ dbuser }}'
      password: '{{ dbpass }}'
      priv: '*.*:ALL'
      host: '%'
      state: present
